import { CountryInfo } from './types';

export const generateCountryInfo = (language: string): CountryInfo[] => {
  // Map of country names in different languages
  const countryNames: Record<string, Record<string, string>> = {
    en: {
      AD: 'Andorra',
      AE: 'United Arab Emirates',
      AF: 'Afghanistan',
      AG: 'Antigua and Barbuda',
      AI: 'Anguilla',
      AL: 'Albania',
      AM: 'Armenia',
      AO: 'Angola',
      AQ: 'Antarctica',
      AR: 'Argentina',
      AS: 'American Samoa',
      AT: 'Austria',
      AU: 'Australia',
      AW: 'Aruba',
      AX: 'Alland Islands',
      AZ: 'Azerbaijan',
      BA: 'Bosnia and Herzegovina',
      BB: 'Barbados',
      BD: 'Bangladesh',
      BE: 'Belgium',
      BF: 'Burkina Faso',
      BG: 'Bulgaria',
      BH: 'Bahrain',
      BI: 'Burundi',
      BJ: 'Benin',
      BL: 'Saint Barthelemy',
      BM: 'Bermuda',
      BN: 'Brunei Darussalam',
      BO: 'Bolivia',
      BR: 'Brazil',
      BS: 'Bahamas',
      BT: 'Bhutan',
      BV: 'Bouvet Island',
      BW: 'Botswana',
      BY: 'Belarus',
      BZ: 'Belize',
      CA: 'Canada',
      CC: 'Cocos (Keeling) Islands',
      CD: 'Congo, Democratic Republic of the',
      CF: 'Central African Republic',
      CG: 'Congo, Republic of the',
      CH: 'Switzerland',
      CI: "Cote d'Ivoire",
      CK: 'Cook Islands',
      CL: 'Chile',
      CM: 'Cameroon',
      CN: 'China',
      CO: 'Colombia',
      CR: 'Costa Rica',
      CU: 'Cuba',
      CV: 'Cape Verde',
      CW: 'Curacao',
      CX: 'Christmas Island',
      CY: 'Cyprus',
      CZ: 'Czech Republic',
      DE: 'Germany',
      DJ: 'Djibouti',
      DK: 'Denmark',
      DM: 'Dominica',
      DO: 'Dominican Republic',
      DZ: 'Algeria',
      EC: 'Ecuador',
      EE: 'Estonia',
      EG: 'Egypt',
      EH: 'Western Sahara',
      ER: 'Eritrea',
      ES: 'Spain',
      ET: 'Ethiopia',
      FI: 'Finland',
      FJ: 'Fiji',
      FK: 'Falkland Islands (Malvinas)',
      FM: 'Micronesia, Federated States of',
      FO: 'Faroe Islands',
      FR: 'France',
      GA: 'Gabon',
      GB: 'United Kingdom',
      GD: 'Grenada',
      GE: 'Georgia',
      GF: 'French Guiana',
      GG: 'Guernsey',
      GH: 'Ghana',
      GI: 'Gibraltar',
      GL: 'Greenland',
      GM: 'Gambia',
      GN: 'Guinea',
      GP: 'Guadeloupe',
      GQ: 'Equatorial Guinea',
      GR: 'Greece',
      GS: 'South Georgia and the South Sandwich Islands',
      GT: 'Guatemala',
      GU: 'Guam',
      GW: 'Guinea-Bissau',
      GY: 'Guyana',
      HK: 'Hong Kong',
      HM: 'Heard Island and McDonald Islands',
      HN: 'Honduras',
      HR: 'Croatia',
      HT: 'Haiti',
      HU: 'Hungary',
      ID: 'Indonesia',
      IE: 'Ireland',
      IL: 'Israel',
      IM: 'Isle of Man',
      IN: 'India',
      IO: 'British Indian Ocean Territory',
      IQ: 'Iraq',
      IR: 'Iran, Islamic Republic of',
      IS: 'Iceland',
      IT: 'Italy',
      JE: 'Jersey',
      JM: 'Jamaica',
      JO: 'Jordan',
      JP: 'Japan',
      KE: 'Kenya',
      KG: 'Kyrgyzstan',
      KH: 'Cambodia',
      KI: 'Kiribati',
      KM: 'Comoros',
      KN: 'Saint Kitts and Nevis',
      KP: "Korea, Democratic People's Republic of",
      KR: 'Korea, Republic of',
      KW: 'Kuwait',
      KY: 'Cayman Islands',
      KZ: 'Kazakhstan',
      LA: "Lao People's Democratic Republic",
      LB: 'Lebanon',
      LC: 'Saint Lucia',
      LI: 'Liechtenstein',
      LK: 'Sri Lanka',
      LR: 'Liberia',
      LS: 'Lesotho',
      LT: 'Lithuania',
      LU: 'Luxembourg',
      LV: 'Latvia',
      LY: 'Libya',
      MA: 'Morocco',
      MC: 'Monaco',
      MD: 'Moldova, Republic of',
      ME: 'Montenegro',
      MF: 'Saint Martin (French part)',
      MG: 'Madagascar',
      MH: 'Marshall Islands',
      MK: 'Macedonia, the Former Yugoslav Republic of',
      ML: 'Mali',
      MM: 'Myanmar',
      MN: 'Mongolia',
      MO: 'Macao',
      MP: 'Northern Mariana Islands',
      MQ: 'Martinique',
      MR: 'Mauritania',
      MS: 'Montserrat',
      MT: 'Malta',
      MU: 'Mauritius',
      MV: 'Maldives',
      MW: 'Malawi',
      MX: 'Mexico',
      MY: 'Malaysia',
      MZ: 'Mozambique',
      NA: 'Namibia',
      NC: 'New Caledonia',
      NE: 'Niger',
      NF: 'Norfolk Island',
      NG: 'Nigeria',
      NI: 'Nicaragua',
      NL: 'Netherlands',
      NO: 'Norway',
      NP: 'Nepal',
      NR: 'Nauru',
      NU: 'Niue',
      NZ: 'New Zealand',
      OM: 'Oman',
      PA: 'Panama',
      PE: 'Peru',
      PF: 'French Polynesia',
      PG: 'Papua New Guinea',
      PH: 'Philippines',
      PK: 'Pakistan',
      PL: 'Poland',
      PM: 'Saint Pierre and Miquelon',
      PN: 'Pitcairn',
      PR: 'Puerto Rico',
      PS: 'Palestine, State of',
      PT: 'Portugal',
      PW: 'Palau',
      PY: 'Paraguay',
      QA: 'Qatar',
      RE: 'Reunion',
      RO: 'Romania',
      RS: 'Serbia',
      RU: 'Russian Federation',
      RW: 'Rwanda',
      SA: 'Saudi Arabia',
      SB: 'Solomon Islands',
      SC: 'Seychelles',
      SD: 'Sudan',
      SE: 'Sweden',
      SG: 'Singapore',
      SH: 'Saint Helena',
      SI: 'Slovenia',
      SJ: 'Svalbard and Jan Mayen',
      SK: 'Slovakia',
      SL: 'Sierra Leone',
      SM: 'San Marino',
      SN: 'Senegal',
      SO: 'Somalia',
      SR: 'Suriname',
      SS: 'South Sudan',
      ST: 'Sao Tome and Principe',
      SV: 'El Salvador',
      SX: 'Sint Maarten (Dutch part)',
      SY: 'Syrian Arab Republic',
      SZ: 'Swaziland',
      TC: 'Turks and Caicos Islands',
      TD: 'Chad',
      TF: 'French Southern Territories',
      TG: 'Togo',
      TH: 'Thailand',
      TJ: 'Tajikistan',
      TK: 'Tokelau',
      TL: 'Timor-Leste',
      TM: 'Turkmenistan',
      TN: 'Tunisia',
      TO: 'Tonga',
      TR: 'Turkey',
      TT: 'Trinidad and Tobago',
      TV: 'Tuvalu',
      TW: 'Taiwan',
      TZ: 'United Republic of Tanzania',
      UA: 'Ukraine',
      UG: 'Uganda',
      US: 'United States',
      UY: 'Uruguay',
      UZ: 'Uzbekistan',
      VA: 'Holy See (Vatican City State)',
      VC: 'Saint Vincent and the Grenadines',
      VE: 'Venezuela',
      VG: 'British Virgin Islands',
      VI: 'US Virgin Islands',
      VN: 'Vietnam',
      VU: 'Vanuatu',
      WF: 'Wallis and Futuna',
      WS: 'Samoa',
      XK: 'Kosovo',
      YE: 'Yemen',
      YT: 'Mayotte',
      ZA: 'South Africa',
      ZM: 'Zambia',
      ZW: 'Zimbabwe',
    },
    es: {
      AD: 'Andorra',
      AE: 'Emiratos Árabes Unidos',
      AF: 'Afganistán',
      AG: 'Antigua y Barbuda',
      AI: 'Anguila',
      AL: 'Albania',
      AM: 'Armenia',
      AO: 'Angola',
      AQ: 'Antártida',
      AR: 'Argentina',
      AS: 'Samoa Americana',
      AT: 'Austria',
      AU: 'Australia',
      AW: 'Aruba',
      AX: 'Islas Åland',
      AZ: 'Azerbaiyán',
      BA: 'Bosnia y Herzegovina',
      BB: 'Barbados',
      BD: 'Bangladés',
      BE: 'Bélgica',
      BF: 'Burkina Faso',
      BG: 'Bulgaria',
      BH: 'Baréin',
      BI: 'Burundi',
      BJ: 'Benín',
      BL: 'San Bartolomé',
      BM: 'Bermudas',
      BN: 'Brunéi',
      BO: 'Bolivia',
      BQ: 'Caribe neerlandés',
      BR: 'Brasil',
      BS: 'Bahamas',
      BT: 'Bután',
      BV: 'Isla Bouvet',
      BW: 'Botsuana',
      BY: 'Bielorrusia',
      BZ: 'Belice',
      CA: 'Canadá',
      CC: 'Islas Cocos',
      CD: 'Congo (Rep. Dem.)',
      CF: 'República Centroafricana',
      CG: 'Congo',
      CH: 'Suiza',
      CI: 'Costa de Marfil',
      CK: 'Islas Cook',
      CL: 'Chile',
      CM: 'Camerún',
      CN: 'China',
      CO: 'Colombia',
      CR: 'Costa Rica',
      CU: 'Cuba',
      CV: 'Cabo Verde',
      CW: 'Curazao',
      CX: 'Isla de Navidad',
      CY: 'Chipre',
      CZ: 'Chequia',
      DE: 'Alemania',
      DJ: 'Yibuti',
      DK: 'Dinamarca',
      DM: 'Dominica',
      DO: 'República Dominicana',
      DZ: 'Argelia',
      EC: 'Ecuador',
      EE: 'Estonia',
      EG: 'Egipto',
      EH: 'Sáhara Occidental',
      ER: 'Eritrea',
      ES: 'España',
      ET: 'Etiopía',
      FI: 'Finlandia',
      FJ: 'Fiyi',
      FK: 'Islas Malvinas',
      FM: 'Micronesia',
      FO: 'Islas Feroe',
      FR: 'Francia',
      GA: 'Gabón',
      GB: 'Reino Unido',
      GD: 'Granada',
      GE: 'Georgia',
      GF: 'Guayana Francesa',
      GG: 'Guernsey',
      GH: 'Ghana',
      GI: 'Gibraltar',
      GL: 'Groenlandia',
      GM: 'Gambia',
      GN: 'Guinea',
      GP: 'Guadalupe',
      GQ: 'Guinea Ecuatorial',
      GR: 'Grecia',
      GS: 'Islas Georgias del Sur y Sandwich del Sur',
      GT: 'Guatemala',
      GU: 'Guam',
      GW: 'Guinea-Bisáu',
      GY: 'Guyana',
      HK: 'Hong Kong',
      HM: 'Islas Heard y McDonald',
      HN: 'Honduras',
      HR: 'Croacia',
      HT: 'Haití',
      HU: 'Hungría',
      ID: 'Indonesia',
      IE: 'Irlanda',
      IL: 'Israel',
      IM: 'Isla de Man',
      IN: 'India',
      IO: 'Territorio Británico del Océano Índico',
      IQ: 'Irak',
      IR: 'Irán',
      IS: 'Islandia',
      IT: 'Italia',
      JE: 'Jersey',
      JM: 'Jamaica',
      JO: 'Jordania',
      JP: 'Japón',
      KE: 'Kenia',
      KG: 'Kirguistán',
      KH: 'Camboya',
      KI: 'Kiribati',
      KM: 'Comoras',
      KN: 'San Cristóbal y Nieves',
      KP: 'Corea del Norte',
      KR: 'Corea del Sur',
      KW: 'Kuwait',
      KY: 'Islas Caimán',
      KZ: 'Kazajistán',
      LA: 'Laos',
      LB: 'Líbano',
      LC: 'Santa Lucía',
      LI: 'Liechtenstein',
      LK: 'Sri Lanka',
      LR: 'Liberia',
      LS: 'Lesoto',
      LT: 'Lituania',
      LU: 'Luxemburgo',
      LV: 'Letonia',
      LY: 'Libia',
      MA: 'Marruecos',
      MC: 'Mónaco',
      MD: 'Moldavia',
      ME: 'Montenegro',
      MF: 'San Martín',
      MG: 'Madagascar',
      MH: 'Islas Marshall',
      MK: 'Macedonia del Norte',
      ML: 'Mali',
      MM: 'Birmania',
      MN: 'Mongolia',
      MO: 'Macao',
      MP: 'Islas Marianas del Norte',
      MQ: 'Martinica',
      MR: 'Mauritania',
      MS: 'Montserrat',
      MT: 'Malta',
      MU: 'Mauricio',
      MV: 'Maldivas',
      MW: 'Malaui',
      MX: 'México',
      MY: 'Malasia',
      MZ: 'Mozambique',
      NA: 'Namibia',
      NC: 'Nueva Caledonia',
      NE: 'Níger',
      NF: 'Isla Norfolk',
      NG: 'Nigeria',
      NI: 'Nicaragua',
      NL: 'Países Bajos',
      NO: 'Noruega',
      NP: 'Nepal',
      NR: 'Nauru',
      NU: 'Niue',
      NZ: 'Nueva Zelanda',
      OM: 'Omán',
      PA: 'Panamá',
      PE: 'Perú',
      PF: 'Polinesia Francesa',
      PG: 'Papúa Nueva Guinea',
      PH: 'Filipinas',
      PK: 'Pakistán',
      PL: 'Polonia',
      PM: 'San Pedro y Miquelón',
      PN: 'Pitcairn',
      PR: 'Puerto Rico',
      PS: 'Estado de Palestina',
      PT: 'Portugal',
      PW: 'Palaos',
      PY: 'Paraguay',
      QA: 'Catar',
      RE: 'Reunión',
      RO: 'Rumania',
      RS: 'Serbia',
      RU: 'Rusia',
      RW: 'Ruanda',
      SA: 'Arabia Saudita',
      SB: 'Islas Salomón',
      SC: 'Seychelles',
      SD: 'Sudán',
      SE: 'Suecia',
      SG: 'Singapur',
      SH: 'Santa Elena, Ascensión y Tristán de Acuña',
      SI: 'Eslovenia',
      SJ: 'Svalbard y Jan Mayen',
      SK: 'Eslovaquia',
      SL: 'Sierra Leona',
      SM: 'San Marino',
      SN: 'Senegal',
      SO: 'Somalia',
      SR: 'Surinam',
      SS: 'Sudán del Sur',
      ST: 'Santo Tomé y Príncipe',
      SV: 'El Salvador',
      SX: 'Sint Maarten',
      SY: 'Siria',
      SZ: 'Suazilandia',
      TC: 'Islas Turcas y Caicos',
      TD: 'Chad',
      TF: 'Territorios Australes Franceses',
      TG: 'Togo',
      TH: 'Tailandia',
      TJ: 'Tayikistán',
      TK: 'Tokelau',
      TL: 'Timor Oriental',
      TM: 'Turkmenistán',
      TN: 'Túnez',
      TO: 'Tonga',
      TR: 'Turquía',
      TT: 'Trinidad y Tobago',
      TV: 'Tuvalu',
      TW: 'Taiwán',
      TZ: 'Tanzania',
      UA: 'Ucrania',
      UG: 'Uganda',
      UM: 'Islas menores alejadas de los Estados Unidos',
      US: 'Estados Unidos',
      UY: 'Uruguay',
      UZ: 'Uzbekistán',
      VA: 'Ciudad del Vaticano',
      VC: 'San Vicente y las Granadinas',
      VE: 'Venezuela',
      VG: 'Islas Vírgenes Británicas',
      VI: 'Islas Vírgenes de los Estados Unidos',
      VN: 'Vietnam',
      VU: 'Vanuatu',
      WF: 'Wallis y Futuna',
      WS: 'Samoa',
      YE: 'Yemen',
      YT: 'Mayotte',
      ZA: 'Sudáfrica',
      ZM: 'Zambia',
      ZW: 'Zimbabue',
    },
    de: {
      AD: 'Andorra',
      AE: 'Vereinigte Arabische Emirate',
      AF: 'Afghanistan',
      AG: 'Antigua und Barbuda',
      AI: 'Anguilla',
      AL: 'Albanien',
      AM: 'Armenien',
      AO: 'Angola',
      AQ: 'Antarktis',
      AR: 'Argentinien',
      AS: 'Amerikanisch-Samoa',
      AT: 'Österreich',
      AU: 'Australien',
      AW: 'Aruba',
      AX: 'Ålandinseln',
      AZ: 'Aserbaidschan',
      BA: 'Bosnien und Herzegowina',
      BB: 'Barbados',
      BD: 'Bangladesch',
      BE: 'Belgien',
      BF: 'Burkina Faso',
      BG: 'Bulgarien',
      BH: 'Bahrain',
      BI: 'Burundi',
      BJ: 'Benin',
      BL: 'Saint-Barthélemy',
      BM: 'Bermuda',
      BN: 'Brunei Darussalam',
      BO: 'Bolivien',
      BQ: 'Bonaire, Sint Eustatius und Saba',
      BR: 'Brasilien',
      BS: 'Bahamas',
      BT: 'Bhutan',
      BV: 'Bouvetinsel',
      BW: 'Botswana',
      BY: 'Weißrussland',
      BZ: 'Belize',
      CA: 'Kanada',
      CC: 'Kokosinseln',
      CD: 'Kongo, Demokratische Republik',
      CF: 'Zentralafrikanische Republik',
      CG: 'Kongo, Republik',
      CH: 'Schweiz',
      CI: "Côte d'Ivoire",
      CK: 'Cookinseln',
      CL: 'Chile',
      CM: 'Kamerun',
      CN: 'China',
      CO: 'Kolumbien',
      CR: 'Costa Rica',
      CU: 'Kuba',
      CV: 'Cabo Verde',
      CW: 'Curaçao',
      CX: 'Weihnachtsinsel',
      CY: 'Zypern',
      CZ: 'Tschechien',
      DE: 'Deutschland',
      DJ: 'Dschibuti',
      DK: 'Dänemark',
      DM: 'Dominica',
      DO: 'Dominikanische Republik',
      DZ: 'Algerien',
      EC: 'Ecuador',
      EE: 'Estland',
      EG: 'Ägypten',
      EH: 'Westsahara',
      ER: 'Eritrea',
      ES: 'Spanien',
      ET: 'Äthiopien',
      FI: 'Finnland',
      FJ: 'Fidschi',
      FK: 'Falklandinseln',
      FM: 'Mikronesien',
      FO: 'Färöer',
      FR: 'Frankreich',
      GA: 'Gabun',
      GB: 'Vereinigtes Königreich',
      GD: 'Grenada',
      GE: 'Georgien',
      GF: 'Französisch-Guayana',
      GG: 'Guernsey',
      GH: 'Ghana',
      GI: 'Gibraltar',
      GL: 'Grönland',
      GM: 'Gambia',
      GN: 'Guinea',
      GP: 'Guadeloupe',
      GQ: 'Äquatorialguinea',
      GR: 'Griechenland',
      GS: 'Südgeorgien und die Südlichen Sandwichinseln',
      GT: 'Guatemala',
      GU: 'Guam',
      GW: 'Guinea-Bissau',
      GY: 'Guyana',
      HK: 'Hongkong',
      HM: 'Heard und McDonaldinseln',
      HN: 'Honduras',
      HR: 'Kroatien',
      HT: 'Haiti',
      HU: 'Ungarn',
      ID: 'Indonesien',
      IE: 'Irland',
      IL: 'Israel',
      IM: 'Isle of Man',
      IN: 'Indien',
      IO: 'Britisches Territorium im Indischen Ozean',
      IQ: 'Irak',
      IR: 'Iran, Islamische Republik',
      IS: 'Island',
      IT: 'Italien',
      JE: 'Jersey',
      JM: 'Jamaika',
      JO: 'Jordanien',
      JP: 'Japan',
      KE: 'Kenia',
      KG: 'Kirgisistan',
      KH: 'Kambodscha',
      KI: 'Kiribati',
      KM: 'Komoren',
      KN: 'St. Kitts und Nevis',
      KP: 'Korea, Demokratische Volksrepublik',
      KR: 'Korea, Republik',
      KW: 'Kuwait',
      KY: 'Kaimaninseln',
      KZ: 'Kasachstan',
      LA: 'Laos, Demokratische Volksrepublik',
      LB: 'Libanon',
      LC: 'St. Lucia',
      LI: 'Liechtenstein',
      LK: 'Sri Lanka',
      LR: 'Liberia',
      LS: 'Lesotho',
      LT: 'Litauen',
      LU: 'Luxemburg',
      LV: 'Lettland',
      LY: 'Libyen',
      MA: 'Marokko',
      MC: 'Monaco',
      MD: 'Republik Moldau',
      ME: 'Montenegro',
      MF: 'Saint-Martin',
      MG: 'Madagaskar',
      MH: 'Marshallinseln',
      MK: 'Mazedonien, ehemalige jugoslawische Republik',
      ML: 'Mali',
      MM: 'Myanmar',
      MN: 'Mongolei',
      MO: 'Macao',
      MP: 'Nördliche Marianen',
      MQ: 'Martinique',
      MR: 'Mauretanien',
      MS: 'Montserrat',
      MT: 'Malta',
      MU: 'Mauritius',
      MV: 'Malediven',
      MW: 'Malawi',
      MX: 'Mexiko',
      MY: 'Malaysia',
      MZ: 'Mosambik',
      NA: 'Namibia',
      NC: 'Neukaledonien',
      NE: 'Niger',
      NF: 'Norfolkinsel',
      NG: 'Nigeria',
      NI: 'Nicaragua',
      NL: 'Niederlande',
      NO: 'Norwegen',
      NP: 'Nepal',
      NR: 'Nauru',
      NU: 'Niue',
      NZ: 'Neuseeland',
      OM: 'Oman',
      PA: 'Panama',
      PE: 'Peru',
      PF: 'Französisch-Polynesien',
      PG: 'Papua-Neuguinea',
      PH: 'Philippinen',
      PK: 'Pakistan',
      PL: 'Polen',
      PM: 'St. Pierre und Miquelon',
      PN: 'Pitcairninseln',
      PR: 'Puerto Rico',
      PS: 'Palästinensische Gebiete',
      PT: 'Portugal',
      PW: 'Palau',
      PY: 'Paraguay',
      QA: 'Katar',
      RE: 'Réunion',
      RO: 'Rumänien',
      RS: 'Serbien',
      RU: 'Russische Föderation',
      RW: 'Ruanda',
      SA: 'Saudi-Arabien',
      SB: 'Salomonen',
      SC: 'Seychellen',
      SD: 'Sudan',
      SE: 'Schweden',
      SG: 'Singapur',
      SH: 'St. Helena, Ascension und Tristan da Cunha',
      SI: 'Slowenien',
      SJ: 'Svalbard und Jan Mayen',
      SK: 'Slowakei',
      SL: 'Sierra Leone',
      SM: 'San Marino',
      SN: 'Senegal',
      SO: 'Somalia',
      SR: 'Suriname',
      SS: 'Südsudan',
      ST: 'São Tomé und Príncipe',
      SV: 'El Salvador',
      SX: 'Sint Maarten',
      SY: 'Syrien, Arabische Republik',
      SZ: 'Eswatini',
      TC: 'Turks- und Caicosinseln',
      TD: 'Tschad',
      TF: 'Französische Süd- und Antarktisgebiete',
      TG: 'Togo',
      TH: 'Thailand',
      TJ: 'Tadschikistan',
      TK: 'Tokelau',
      TL: 'Timor-Leste',
      TM: 'Turkmenistan',
      TN: 'Tunesien',
      TO: 'Tonga',
      TR: 'Türkei',
      TT: 'Trinidad und Tobago',
      TV: 'Tuvalu',
      TW: 'Taiwan',
      TZ: 'Tansania, Vereinigte Republik',
      UA: 'Ukraine',
      UG: 'Uganda',
      UM: 'Amerikanische Überseeinseln',
      US: 'Vereinigte Staaten von Amerika',
      UY: 'Uruguay',
      UZ: 'Usbekistan',
      VA: 'Heiliger Stuhl',
      VC: 'St. Vincent und die Grenadinen',
      VE: 'Venezuela',
      VG: 'Britische Jungferninseln',
      VI: 'Amerikanische Jungferninseln',
      VN: 'Vietnam',
      VU: 'Vanuatu',
      WF: 'Wallis und Futuna',
      WS: 'Samoa',
      YE: 'Jemen',
      YT: 'Mayotte',
      ZA: 'Südafrika',
      ZM: 'Sambia',
      ZW: 'Simbabwe',
    },
    fr: {
      AD: 'Andorre',
      AE: 'Émirats arabes unis',
      AF: 'Afghanistan',
      AG: 'Antigua-et-Barbuda',
      AI: 'Anguilla',
      AL: 'Albanie',
      AM: 'Arménie',
      AO: 'Angola',
      AQ: 'Antarctique',
      AR: 'Argentine',
      AS: 'Samoa américaines',
      AT: 'Autriche',
      AU: 'Australie',
      AW: 'Aruba',
      AX: 'Îles Åland',
      AZ: 'Azerbaïdjan',
      BA: 'Bosnie-Herzégovine',
      BB: 'Barbade',
      BD: 'Bangladesh',
      BE: 'Belgique',
      BF: 'Burkina Faso',
      BG: 'Bulgarie',
      BH: 'Bahreïn',
      BI: 'Burundi',
      BJ: 'Bénin',
      BL: 'Saint-Barthélemy',
      BM: 'Bermudes',
      BN: 'Brunéi Darussalam',
      BO: 'Bolivie',
      BQ: 'Bonaire, Saint-Eustache et Saba',
      BR: 'Brésil',
      BS: 'Bahamas',
      BT: 'Bhoutan',
      BV: 'Île Bouvet',
      BW: 'Botswana',
      BY: 'Bélarus',
      BZ: 'Belize',
      CA: 'Canada',
      CC: 'Îles Cocos',
      CD: 'Congo-Kinshasa',
      CF: 'République centrafricaine',
      CG: 'Congo-Brazzaville',
      CH: 'Suisse',
      CI: "Côte d'Ivoire",
      CK: 'Îles Cook',
      CL: 'Chili',
      CM: 'Cameroun',
      CN: 'Chine',
      CO: 'Colombie',
      CR: 'Costa Rica',
      CU: 'Cuba',
      CV: 'Cap-Vert',
      CW: 'Curaçao',
      CX: 'Île Christmas',
      CY: 'Chypre',
      CZ: 'Tchéquie',
      DE: 'Allemagne',
      DJ: 'Djibouti',
      DK: 'Danemark',
      DM: 'Dominique',
      DO: 'République dominicaine',
      DZ: 'Algérie',
      EC: 'Équateur',
      EE: 'Estonie',
      EG: 'Égypte',
      EH: 'Sahara occidental',
      ER: 'Érythrée',
      ES: 'Espagne',
      ET: 'Éthiopie',
      FI: 'Finlande',
      FJ: 'Fidji',
      FK: 'Îles Malouines',
      FM: 'Micronésie',
      FO: 'Îles Féroé',
      FR: 'France',
      GA: 'Gabon',
      GB: 'Royaume-Uni',
      GD: 'Grenade',
      GE: 'Géorgie',
      GF: 'Guyane française',
      GG: 'Guernesey',
      GH: 'Ghana',
      GI: 'Gibraltar',
      GL: 'Groenland',
      GM: 'Gambie',
      GN: 'Guinée',
      GP: 'Guadeloupe',
      GQ: 'Guinée équatoriale',
      GR: 'Grèce',
      GS: 'Géorgie du Sud-et-les Îles Sandwich du Sud',
      GT: 'Guatemala',
      GU: 'Guam',
      GW: 'Guinée-Bissau',
      GY: 'Guyana',
      HK: 'Hong Kong',
      HM: 'Îles Heard-et-MacDonald',
      HN: 'Honduras',
      HR: 'Croatie',
      HT: 'Haïti',
      HU: 'Hongrie',
      ID: 'Indonésie',
      IE: 'Irlande',
      IL: 'Israël',
      IM: 'Île de Man',
      IN: 'Inde',
      IO: "Territoire britannique de l'océan Indien",
      IQ: 'Irak',
      IR: 'Iran',
      IS: 'Islande',
      IT: 'Italie',
      JE: 'Jersey',
      JM: 'Jamaïque',
      JO: 'Jordanie',
      JP: 'Japon',
      KE: 'Kenya',
      KG: 'Kirghizistan',
      KH: 'Cambodge',
      KI: 'Kiribati',
      KM: 'Comores',
      KN: 'Saint-Christophe-et-Niévès',
      KP: 'Corée du Nord',
      KR: 'Corée du Sud',
      KW: 'Koweït',
      KY: 'Îles Caïmans',
      KZ: 'Kazakhstan',
      LA: 'Laos',
      LB: 'Liban',
      LC: 'Sainte-Lucie',
      LI: 'Liechtenstein',
      LK: 'Sri Lanka',
      LR: 'Libéria',
      LS: 'Lesotho',
      LT: 'Lituanie',
      LU: 'Luxembourg',
      LV: 'Lettonie',
      LY: 'Libye',
      MA: 'Maroc',
      MC: 'Monaco',
      MD: 'Moldavie',
      ME: 'Monténégro',
      MF: 'Saint-Martin',
      MG: 'Madagascar',
      MH: 'Îles Marshall',
      MK: 'Macédoine du Nord',
      ML: 'Mali',
      MM: 'Myanmar',
      MN: 'Mongolie',
      MO: 'Macao',
      MP: 'Îles Mariannes du Nord',
      MQ: 'Martinique',
      MR: 'Mauritanie',
      MS: 'Montserrat',
      MT: 'Malte',
      MU: 'Maurice',
      MV: 'Maldives',
      MW: 'Malawi',
      MX: 'Mexique',
      MY: 'Malaisie',
      MZ: 'Mozambique',
      NA: 'Namibie',
      NC: 'Nouvelle-Calédonie',
      NE: 'Niger',
      NF: 'Île Norfolk',
      NG: 'Nigeria',
      NI: 'Nicaragua',
      NL: 'Pays-Bas',
      NO: 'Norvège',
      NP: 'Népal',
      NR: 'Nauru',
      NU: 'Niue',
      NZ: 'Nouvelle-Zélande',
      OM: 'Oman',
      PA: 'Panama',
      PE: 'Pérou',
      PF: 'Polynésie française',
      PG: 'Papouasie-Nouvelle-Guinée',
      PH: 'Philippines',
      PK: 'Pakistan',
      PL: 'Pologne',
      PM: 'Saint-Pierre-et-Miquelon',
      PN: 'Îles Pitcairn',
      PR: 'Porto Rico',
      PS: 'Palestine',
      PT: 'Portugal',
      PW: 'Palaos',
      PY: 'Paraguay',
      QA: 'Qatar',
      RE: 'Réunion',
      RO: 'Roumanie',
      RS: 'Serbie',
      RU: 'Russie',
      RW: 'Rwanda',
      SA: 'Arabie saoudite',
      SB: 'Îles Salomon',
      SC: 'Seychelles',
      SD: 'Soudan',
      SE: 'Suède',
      SG: 'Singapour',
      SH: 'Sainte-Hélène',
      SI: 'Slovénie',
      SJ: 'Svalbard et Île Jan Mayen',
      SK: 'Slovaquie',
      SL: 'Sierra Leone',
      SM: 'Saint-Marin',
      SN: 'Sénégal',
      SO: 'Somalie',
      SR: 'Suriname',
      SS: 'Soudan du Sud',
      ST: 'Sao Tomé-et-Principe',
      SV: 'Salvador',
      SX: 'Saint-Martin (partie néerlandaise)',
      SY: 'Syrie',
      SZ: 'Eswatini',
      TC: 'Îles Turques-et-Caïques',
      TD: 'Tchad',
      TF: 'Terres australes françaises',
      TG: 'Togo',
      TH: 'Thaïlande',
      TJ: 'Tadjikistan',
      TK: 'Tokelau',
      TL: 'Timor oriental',
      TM: 'Turkménistan',
      TN: 'Tunisie',
      TO: 'Tonga',
      TR: 'Turquie',
      TT: 'Trinité-et-Tobago',
      TV: 'Tuvalu',
      TW: 'Taïwan',
      TZ: 'Tanzanie',
      UA: 'Ukraine',
      UG: 'Ouganda',
      UM: 'Îles mineures éloignées des États-Unis',
      US: 'États-Unis',
      UY: 'Uruguay',
      UZ: 'Ouzbékistan',
      VA: 'Cité du Vatican',
      VC: 'Saint-Vincent-et-les Grenadines',
      VE: 'Venezuela',
      VG: 'Îles Vierges britanniques',
      VI: 'Îles Vierges américaines',
      VN: 'Viêt Nam',
      VU: 'Vanuatu',
      WF: 'Wallis-et-Futuna',
      WS: 'Samoa',
      YE: 'Yémen',
      YT: 'Mayotte',
      ZA: 'Afrique du Sud',
      ZM: 'Zambie',
      ZW: 'Zimbabwe',
    },
    it: {
      AD: 'Andorra',
      AE: 'Emirati Arabi Uniti',
      AF: 'Afghanistan',
      AG: 'Antigua e Barbuda',
      AI: 'Anguilla',
      AL: 'Albania',
      AM: 'Armenia',
      AO: 'Angola',
      AQ: 'Antartide',
      AR: 'Argentina',
      AS: 'Samoa Americane',
      AT: 'Austria',
      AU: 'Australia',
      AW: 'Aruba',
      AX: 'Isole Aland',
      AZ: 'Azerbaigian',
      BA: 'Bosnia-Erzegovina',
      BB: 'Barbados',
      BD: 'Bangladesh',
      BE: 'Belgio',
      BF: 'Burkina Faso',
      BG: 'Bulgaria',
      BH: 'Bahrein',
      BI: 'Burundi',
      BJ: 'Benin',
      BL: 'Saint-Barthélemy',
      BM: 'Bermuda',
      BN: 'Brunei',
      BO: 'Bolivia',
      BQ: 'Caraibi olandesi',
      BR: 'Brasile',
      BS: 'Bahamas',
      BT: 'Bhutan',
      BV: 'Isola Bouvet',
      BW: 'Botswana',
      BY: 'Bielorussia',
      BZ: 'Belize',
      CA: 'Canada',
      CC: 'Isole Cocos',
      CD: 'Congo-Kinshasa',
      CF: 'Repubblica Centrafricana',
      CG: 'Congo-Brazzaville',
      CH: 'Svizzera',
      CI: "Costa d'Avorio",
      CK: 'Isole Cook',
      CL: 'Cile',
      CM: 'Camerun',
      CN: 'Cina',
      CO: 'Colombia',
      CR: 'Costa Rica',
      CU: 'Cuba',
      CV: 'Capo Verde',
      CW: 'Curaçao',
      CX: 'Isola di Natale',
      CY: 'Cipro',
      CZ: 'Repubblica Ceca',
      DE: 'Germania',
      DJ: 'Gibuti',
      DK: 'Danimarca',
      DM: 'Dominica',
      DO: 'Repubblica Dominicana',
      DZ: 'Algeria',
      EC: 'Ecuador',
      EE: 'Estonia',
      EG: 'Egitto',
      EH: 'Sahara Occidentale',
      ER: 'Eritrea',
      ES: 'Spagna',
      ET: 'Etiopia',
      FI: 'Finlandia',
      FJ: 'Figi',
      FK: 'Isole Falkland',
      FM: 'Micronesia',
      FO: 'Isole Fær Øer',
      FR: 'Francia',
      GA: 'Gabon',
      GB: 'Regno Unito',
      GD: 'Grenada',
      GE: 'Georgia',
      GF: 'Guyana francese',
      GG: 'Guernsey',
      GH: 'Ghana',
      GI: 'Gibilterra',
      GL: 'Groenlandia',
      GM: 'Gambia',
      GN: 'Guinea',
      GP: 'Guadalupa',
      GQ: 'Guinea Equatoriale',
      GR: 'Grecia',
      GS: 'Georgia del Sud e Isole Sandwich Meridionali',
      GT: 'Guatemala',
      GU: 'Guam',
      GW: 'Guinea-Bissau',
      GY: 'Guyana',
      HK: 'Hong Kong',
      HM: 'Isole Heard e McDonald',
      HN: 'Honduras',
      HR: 'Croazia',
      HT: 'Haiti',
      HU: 'Ungheria',
      ID: 'Indonesia',
      IE: 'Irlanda',
      IL: 'Israele',
      IM: 'Isola di Man',
      IN: 'India',
      IO: "Territorio britannico dell'Oceano Indiano",
      IQ: 'Iraq',
      IR: 'Iran',
      IS: 'Islanda',
      IT: 'Italia',
      JE: 'Jersey',
      JM: 'Giamaica',
      JO: 'Giordania',
      JP: 'Giappone',
      KE: 'Kenya',
      KG: 'Kirghizistan',
      KH: 'Cambogia',
      KI: 'Kiribati',
      KM: 'Comore',
      KN: 'Saint Kitts e Nevis',
      KP: 'Corea del Nord',
      KR: 'Corea del Sud',
      KW: 'Kuwait',
      KY: 'Isole Cayman',
      KZ: 'Kazakistan',
      LA: 'Laos',
      LB: 'Libano',
      LC: 'Saint Lucia',
      LI: 'Liechtenstein',
      LK: 'Sri Lanka',
      LR: 'Liberia',
      LS: 'Lesotho',
      LT: 'Lituania',
      LU: 'Lussemburgo',
      LV: 'Lettonia',
      LY: 'Libia',
      MA: 'Marocco',
      MC: 'Monaco',
      MD: 'Moldavia',
      ME: 'Montenegro',
      MF: 'Saint Martin',
      MG: 'Madagascar',
      MH: 'Isole Marshall',
      MK: 'Macedonia del Nord',
      ML: 'Mali',
      MM: 'Myanmar',
      MN: 'Mongolia',
      MO: 'Macao',
      MP: 'Isole Marianne Settentrionali',
      MQ: 'Martinica',
      MR: 'Mauritania',
      MS: 'Montserrat',
      MT: 'Malta',
      MU: 'Mauritius',
      MV: 'Maldive',
      MW: 'Malawi',
      MX: 'Messico',
      MY: 'Malesia',
      MZ: 'Mozambico',
      NA: 'Namibia',
      NC: 'Nuova Caledonia',
      NE: 'Niger',
      NF: 'Isola Norfolk',
      NG: 'Nigeria',
      NI: 'Nicaragua',
      NL: 'Paesi Bassi',
      NO: 'Norvegia',
      NP: 'Nepal',
      NR: 'Nauru',
      NU: 'Niue',
      NZ: 'Nuova Zelanda',
      OM: 'Oman',
      PA: 'Panamá',
      PE: 'Perù',
      PF: 'Polinesia Francese',
      PG: 'Papua Nuova Guinea',
      PH: 'Filippine',
      PK: 'Pakistan',
      PL: 'Polonia',
      PM: 'Saint Pierre e Miquelon',
      PN: 'Pitcairn',
      PR: 'Portorico',
      PS: 'Territori palestinesi',
      PT: 'Portogallo',
      PW: 'Palau',
      PY: 'Paraguay',
      QA: 'Qatar',
      RE: 'Riunione',
      RO: 'Romania',
      RS: 'Serbia',
      RU: 'Russia',
      RW: 'Ruanda',
      SA: 'Arabia Saudita',
      SB: 'Isole Salomone',
      SC: 'Seychelles',
      SD: 'Sudan',
      SE: 'Svezia',
      SG: 'Singapore',
      SH: "Sant'Elena, Ascensione e Tristan da Cunha",
      SI: 'Slovenia',
      SJ: 'Svalbard e Jan Mayen',
      SK: 'Slovacchia',
      SL: 'Sierra Leone',
      SM: 'San Marino',
      SN: 'Senegal',
      SO: 'Somalia',
      SR: 'Suriname',
      SS: 'Sud Sudan',
      ST: 'São Tomé e Príncipe',
      SV: 'El Salvador',
      SX: 'Sint Maarten',
      SY: 'Siria',
      SZ: 'Swaziland',
      TC: 'Isole Turks e Caicos',
      TD: 'Ciad',
      TF: 'Territori Francesi del Sud',
      TG: 'Togo',
      TH: 'Thailandia',
      TJ: 'Tagikistan',
      TK: 'Tokelau',
      TL: 'Timor Est',
      TM: 'Turkmenistan',
      TN: 'Tunisia',
      TO: 'Tonga',
      TR: 'Turchia',
      TT: 'Trinidad e Tobago',
      TV: 'Tuvalu',
      TW: 'Taiwan',
      TZ: 'Tanzania',
      UA: 'Ucraina',
      UG: 'Uganda',
      UM: "Isole minori esterne degli Stati Uniti d'America",
      US: 'Stati Uniti',
      UY: 'Uruguay',
      UZ: 'Uzbekistan',
      VA: 'Città del Vaticano',
      VC: 'Saint Vincent e Grenadine',
      VE: 'Venezuela',
      VG: 'Isole Vergini Britanniche',
      VI: 'Isole Vergini Americane',
      VN: 'Vietnam',
      VU: 'Vanuatu',
      WF: 'Wallis e Futuna',
      WS: 'Samoa',
      YE: 'Yemen',
      YT: 'Mayotte',
      ZA: 'Sud Africa',
      ZM: 'Zambia',
      ZW: 'Zimbabwe',
    },
    pt: {
      AD: 'Andorra',
      AE: 'Emirados Árabes Unidos',
      AF: 'Afeganistão',
      AG: 'Antígua e Barbuda',
      AI: 'Anguila',
      AL: 'Albânia',
      AM: 'Armênia',
      AO: 'Angola',
      AQ: 'Antártida',
      AR: 'Argentina',
      AS: 'Samoa Americana',
      AT: 'Áustria',
      AU: 'Austrália',
      AW: 'Aruba',
      AX: 'Ilhas Aland',
      AZ: 'Azerbaijão',
      BA: 'Bósnia e Herzegovina',
      BB: 'Barbados',
      BD: 'Bangladesh',
      BE: 'Bélgica',
      BF: 'Burkina Faso',
      BG: 'Bulgária',
      BH: 'Bahrein',
      BI: 'Burundi',
      BJ: 'Benin',
      BL: 'São Bartolomeu',
      BM: 'Bermudas',
      BN: 'Brunei',
      BO: 'Bolívia',
      BQ: 'Caribe neerlandês',
      BR: 'Brasil',
      BS: 'Bahamas',
      BT: 'Butão',
      BV: 'Ilha Bouvet',
      BW: 'Botsuana',
      BY: 'Bielorrússia',
      BZ: 'Belize',
      CA: 'Canadá',
      CC: 'Ilhas Cocos',
      CD: 'Congo-Kinshasa',
      CF: 'República Centro-Africana',
      CG: 'Congo-Brazzaville',
      CH: 'Suíça',
      CI: 'Costa do Marfim',
      CK: 'Ilhas Cook',
      CL: 'Chile',
      CM: 'Camarões',
      CN: 'China',
      CO: 'Colômbia',
      CR: 'Costa Rica',
      CU: 'Cuba',
      CV: 'Cabo Verde',
      CW: 'Curaçao',
      CX: 'Ilha Christmas',
      CY: 'Chipre',
      CZ: 'República Tcheca',
      DE: 'Alemanha',
      DJ: 'Djibouti',
      DK: 'Dinamarca',
      DM: 'Dominica',
      DO: 'República Dominicana',
      DZ: 'Argélia',
      EC: 'Equador',
      EE: 'Estônia',
      EG: 'Egito',
      EH: 'Saara Ocidental',
      ER: 'Eritreia',
      ES: 'Espanha',
      ET: 'Etiópia',
      FI: 'Finlândia',
      FJ: 'Fiji',
      FK: 'Ilhas Malvinas',
      FM: 'Micronésia',
      FO: 'Ilhas Faroe',
      FR: 'França',
      GA: 'Gabão',
      GB: 'Reino Unido',
      GD: 'Granada',
      GE: 'Geórgia',
      GF: 'Guiana Francesa',
      GG: 'Guernsey',
      GH: 'Gana',
      GI: 'Gibraltar',
      GL: 'Groenlândia',
      GM: 'Gâmbia',
      GN: 'Guiné',
      GP: 'Guadalupe',
      GQ: 'Guiné Equatorial',
      GR: 'Grécia',
      GS: 'Geórgia do Sul e Ilhas Sandwich do Sul',
      GT: 'Guatemala',
      GU: 'Guam',
      GW: 'Guiné-Bissau',
      GY: 'Guiana',
      HK: 'Hong Kong',
      HM: 'Ilhas Heard e McDonald',
      HN: 'Honduras',
      HR: 'Croácia',
      HT: 'Haiti',
      HU: 'Hungria',
      ID: 'Indonésia',
      IE: 'Irlanda',
      IL: 'Israel',
      IM: 'Ilha de Man',
      IN: 'Índia',
      IO: 'Território Britânico do Oceano Índico',
      IQ: 'Iraque',
      IR: 'Irã',
      IS: 'Islândia',
      IT: 'Itália',
      JE: 'Jersey',
      JM: 'Jamaica',
      JO: 'Jordânia',
      JP: 'Japão',
      KE: 'Quênia',
      KG: 'Quirguistão',
      KH: 'Camboja',
      KI: 'Kiribati',
      KM: 'Comores',
      KN: 'São Cristóvão e Nevis',
      KP: 'Coreia do Norte',
      KR: 'Coreia do Sul',
      KW: 'Kuwait',
      KY: 'Ilhas Cayman',
      KZ: 'Cazaquistão',
      LA: 'Laos',
      LB: 'Líbano',
      LC: 'Santa Lúcia',
      LI: 'Liechtenstein',
      LK: 'Sri Lanka',
      LR: 'Libéria',
      LS: 'Lesoto',
      LT: 'Lituânia',
      LU: 'Luxemburgo',
      LV: 'Letônia',
      LY: 'Líbia',
      MA: 'Marrocos',
      MC: 'Mônaco',
      MD: 'Moldávia',
      ME: 'Montenegro',
      MF: 'Saint Martin',
      MG: 'Madagáscar',
      MH: 'Ilhas Marshall',
      MK: 'Macedônia do Norte',
      ML: 'Mali',
      MM: 'Mianmar',
      MN: 'Mongólia',
      MO: 'Macau',
      MP: 'Ilhas Marianas do Norte',
      MQ: 'Martinica',
      MR: 'Mauritânia',
      MS: 'Montserrat',
      MT: 'Malta',
      MU: 'Maurício',
      MV: 'Maldivas',
      MW: 'Malaui',
      MX: 'México',
      MY: 'Malásia',
      MZ: 'Moçambique',
      NA: 'Namíbia',
      NC: 'Nova Caledônia',
      NE: 'Níger',
      NF: 'Ilha Norfolk',
      NG: 'Nigéria',
      NI: 'Nicarágua',
      NL: 'Países Baixos',
      NO: 'Noruega',
      NP: 'Nepal',
      NR: 'Nauru',
      NU: 'Niue',
      NZ: 'Nova Zelândia',
      OM: 'Omã',
      PA: 'Panamá',
      PE: 'Peru',
      PF: 'Polinésia Francesa',
      PG: 'Papua-Nova Guiné',
      PH: 'Filipinas',
      PK: 'Paquistão',
      PL: 'Polônia',
      PM: 'Saint Pierre e Miquelon',
      PN: 'Pitcairn',
      PR: 'Porto Rico',
      PS: 'Territórios Palestinos',
      PT: 'Portugal',
      PW: 'Palau',
      PY: 'Paraguai',
      QA: 'Catar',
      RE: 'Reunião',
      RO: 'Romênia',
      RS: 'Sérvia',
      RU: 'Rússia',
      RW: 'Ruanda',
      SA: 'Arábia Saudita',
      SB: 'Ilhas Salomão',
      SC: 'Seicheles',
      SD: 'Sudão',
      SE: 'Suécia',
      SG: 'Singapura',
      SH: 'Santa Helena, Ascensão e Tristão da Cunha',
      SI: 'Eslovênia',
      SJ: 'Svalbard e Jan Mayen',
      SK: 'Eslováquia',
      SL: 'Serra Leoa',
      SM: 'San Marino',
      SN: 'Senegal',
      SO: 'Somália',
      SR: 'Suriname',
      SS: 'Sudão do Sul',
      ST: 'São Tomé e Príncipe',
      SV: 'El Salvador',
      SX: 'São Martinho',
      SY: 'Síria',
      SZ: 'Suazilândia',
      TC: 'Ilhas Turks e Caicos',
      TD: 'Chade',
      TF: 'Territórios Franceses do Sul',
      TG: 'Togo',
      TH: 'Tailândia',
      TJ: 'Tajiquistão',
      TK: 'Tokelau',
      TL: 'Timor-Leste',
      TM: 'Turcomenistão',
      TN: 'Tunísia',
      TO: 'Tonga',
      TR: 'Turquia',
      TT: 'Trindade e Tobago',
      TV: 'Tuvalu',
      TW: 'Taiwan',
      TZ: 'Tanzânia',
      UA: 'Ucrânia',
      UG: 'Uganda',
      UM: 'Ilhas Menores Distantes dos Estados Unidos',
      US: 'Estados Unidos',
      UY: 'Uruguai',
      UZ: 'Uzbequistão',
      VA: 'Vaticano',
      VC: 'São Vicente e Granadinas',
      VE: 'Venezuela',
      VG: 'Ilhas Virgens Britânicas',
      VI: 'Ilhas Virgens Americanas',
      VN: 'Vietnã',
      VU: 'Vanuatu',
      WF: 'Wallis e Futuna',
      WS: 'Samoa',
      YE: 'Iêmen',
      YT: 'Mayotte',
      ZA: 'África do Sul',
      ZM: 'Zâmbia',
      ZW: 'Zimbábue',
    },
  };

  const countries: CountryInfo[] = [];

  Object.keys(countryNames.en).forEach((code) => {
    const name = countryNames[language]?.[code] || 'Unknown';
    countries.push({ code, name });
  });

  return countries;
};
