import { HobbiesInfo } from "./types";

export const generateHobbiesInfo = (language: string): HobbiesInfo[] => {
    // Map of country names in different languages
    const hobbiesNames: Record<string, Record<string, string>> = {
        en: {
            sports: 'Sports',
            reading: 'Reading',
            cooking: 'Cooking',
            gardening: 'Gardening',
            painting: 'Painting',
            photography: 'Photography',
            hiking: 'Hiking',
            camping: 'Camping',
            fishing: 'Fishing',
            cycling: 'Cycling',
            knitting: 'Knitting',
            writing: 'Writing',
            dancing: 'Dancing',
            gaming: 'Gaming',
            birdWatching: 'Bird Watching',
            traveling: 'Traveling',
            singing: 'Singing',
            yoga: 'Yoga',
            meditation: 'Meditation',
            woodworking: 'Woodworking',
            sculpting: 'Sculpting',
            volunteering: 'Volunteering',
            playingMusic: 'Playing Music',
            collectingStamps: 'Collecting Stamps',
            calligraphy: 'Calligraphy',
            astronomy: 'Astronomy',
            beekeeping: 'Beekeeping',
            embroidery: 'Embroidery',
            stargazing: 'Stargazing',
            bonsai: 'Bonsai'
        },
        es: {
            sports: 'Deportes',
            reading: 'Lectura',
            cooking: 'Cocinar',
            gardening: 'Jardinería',
            painting: 'Pintura',
            photography: 'Fotografía',
            hiking: 'Senderismo',
            camping: 'Camping',
            fishing: 'Pesca',
            cycling: 'Ciclismo',
            knitting: 'Tejer',
            writing: 'Escritura',
            dancing: 'Baile',
            gaming: 'Videojuegos',
            birdWatching: 'Observación de Aves',
            traveling: 'Viajar',
            singing: 'Cantar',
            yoga: 'Yoga',
            meditation: 'Meditación',
            woodworking: 'Carpintería',
            sculpting: 'Escultura',
            volunteering: 'Voluntariado',
            playingMusic: 'Tocar Música',
            collectingStamps: 'Coleccionar Sellos',
            calligraphy: 'Caligrafía',
            astronomy: 'Astronomía',
            beekeeping: 'Apicultura',
            embroidery: 'Bordado',
            stargazing: 'Observación de Estrellas',
            bonsai: 'Bonsái'
        },
        de: {
            sports: 'Sport',
            reading: 'Lesen',
            cooking: 'Kochen',
            gardening: 'Gärtnern',
            painting: 'Malen',
            photography: 'Fotografieren',
            hiking: 'Wandern',
            camping: 'Camping',
            fishing: 'Angeln',
            cycling: 'Radfahren',
            knitting: 'Stricken',
            writing: 'Schreiben',
            dancing: 'Tanzen',
            gaming: 'Spielen',
            birdWatching: 'Vogelbeobachtung',
            traveling: 'Reisen',
            singing: 'Singen',
            yoga: 'Yoga',
            meditation: 'Meditation',
            woodworking: 'Holzarbeit',
            sculpting: 'Skulpturieren',
            volunteering: 'Freiwilligenarbeit',
            playingMusic: 'Musik machen',
            collectingStamps: 'Briefmarkensammeln',
            calligraphy: 'Kalligrafie',
            astronomy: 'Astronomie',
            beekeeping: 'Imkerei',
            embroidery: 'Stickerei',
            stargazing: 'Sterne beobachten',
            bonsai: 'Bonsai'
        },
        fr: {
            sports: 'Sports',
            reading: 'Lecture',
            cooking: 'Cuisine',
            gardening: 'Jardinage',
            painting: 'Peinture',
            photography: 'Photographie',
            hiking: 'Randonnée',
            camping: 'Camping',
            fishing: 'Pêche',
            cycling: 'Cyclisme',
            knitting: 'Tricot',
            writing: 'Écriture',
            dancing: 'Danse',
            gaming: 'Jeux vidéo',
            birdWatching: 'Observation des oiseaux',
            traveling: 'Voyage',
            singing: 'Chant',
            yoga: 'Yoga',
            meditation: 'Méditation',
            woodworking: 'Travail du bois',
            sculpting: 'Sculpture',
            volunteering: 'Bénévolat',
            playingMusic: 'Jouer de la musique',
            collectingStamps: 'Collection de timbres',
            calligraphy: 'Calligraphie',
            astronomy: 'Astronomie',
            beekeeping: 'Apiculture',
            embroidery: 'Broderie',
            stargazing: 'Observation des étoiles',
            bonsai: 'Bonsaï'
        },
        it: {
            sports: 'Sport',
            reading: 'Lettura',
            cooking: 'Cucina',
            gardening: 'Giardinaggio',
            painting: 'Pittura',
            photography: 'Fotografia',
            hiking: 'Escursionismo',
            camping: 'Camping',
            fishing: 'Pesca',
            cycling: 'Ciclismo',
            knitting: 'Lavoro a maglia',
            writing: 'Scrittura',
            dancing: 'Danza',
            gaming: 'Giochi',
            birdWatching: 'Osservazione degli uccelli',
            traveling: 'Viaggi',
            singing: 'Canto',
            yoga: 'Yoga',
            meditation: 'Meditazione',
            woodworking: 'Lavorazione del legno',
            sculpting: 'Scultura',
            volunteering: 'Volontariato',
            playingMusic: 'Suonare la musica',
            collectingStamps: 'Collezione di francobolli',
            calligraphy: 'Calligrafia',
            astronomy: 'Astronomia',
            beekeeping: 'Apicoltura',
            embroidery: 'Ricamo',
            stargazing: 'Osservazione delle stelle',
            bonsai: 'Bonsai'
        },
        pt: {
            sports: 'Esportes',
            reading: 'Leitura',
            cooking: 'Cozinhar',
            gardening: 'Jardinagem',
            painting: 'Pintura',
            photography: 'Fotografia',
            hiking: 'Caminhada',
            camping: 'Camping',
            fishing: 'Pesca',
            cycling: 'Ciclismo',
            knitting: 'Tricô',
            writing: 'Escrita',
            dancing: 'Dança',
            gaming: 'Jogos',
            birdWatching: 'Observação de aves',
            traveling: 'Viajar',
            singing: 'Cantar',
            yoga: 'Yoga',
            meditation: 'Meditação',
            woodworking: 'Trabalho em madeira',
            sculpting: 'Escultura',
            volunteering: 'Voluntariado',
            playingMusic: 'Tocar música',
            collectingStamps: 'Coleção de selos',
            calligraphy: 'Caligrafia',
            astronomy: 'Astronomia',
            beekeeping: 'Apicultura',
            embroidery: 'Bordado',
            stargazing: 'Observação de estrelas',
            bonsai: 'Bonsai'
        },
    };



    const hobbies: HobbiesInfo[] = [];

    Object.keys(hobbiesNames.en).forEach(code => {
        const name = hobbiesNames[language]?.[code] || "Unknown";
        hobbies.push({ code, name });
    });

    return hobbies;
};