import { HobbiesInfo } from './types';

export const generateHobbiesInfo = (language: string): HobbiesInfo[] => {
  // Map of interest names in different languages
  const interestsNames: Record<string, Record<string, string>> = {
    en: {
      sportsFitness: 'Sports and Fitness',
      travel: 'Travel',
      musicEntertainment: 'Music and Entertainment',
      artsCreativity: 'Arts and Creativity',
      readingLearning: 'Reading and Learning',
      technologyGaming: 'Technology and Gaming',
      foodCooking: 'Food and Cooking',
      natureOutdoors: 'Nature and Outdoors',
      socializingRelationships: 'Socializing and Relationships',
      fashionStyle: 'Fashion and Style',
      healthWellness: 'Health and Wellness',
      diyCrafts: 'DIY and Crafts',
      petsAnimalCare: 'Pets and Animal Care',
      carsAutomobiles: 'Cars and Automobiles',
      historyArchaeology: 'History and Archaeology',
      financeInvesting: 'Finance and Investing',
      scienceDiscovery: 'Science and Discovery',
      philosophySpirituality: 'Philosophy and Spirituality',
      volunteeringActivism: 'Volunteering and Activism',
    },
    es: {
      sportsFitness: 'Deportes y Fitness',
      travel: 'Viajes',
      musicEntertainment: 'Música y Entretenimiento',
      artsCreativity: 'Artes y Creatividad',
      readingLearning: 'Lectura y Aprendizaje',
      technologyGaming: 'Tecnología y Juegos',
      foodCooking: 'Comida y Cocina',
      natureOutdoors: 'Naturaleza y Aire Libre',
      socializingRelationships: 'Sociabilización y Relaciones',
      fashionStyle: 'Moda y Estilo',
      healthWellness: 'Salud y Bienestar',
      diyCrafts: 'Bricolaje y Manualidades',
      petsAnimalCare: 'Mascotas y Cuidado de Animales',
      carsAutomobiles: 'Coches y Automóviles',
      historyArchaeology: 'Historia y Arqueología',
      financeInvesting: 'Finanzas e Inversiones',
      scienceDiscovery: 'Ciencia y Descubrimiento',
      philosophySpirituality: 'Filosofía y Espiritualidad',
      volunteeringActivism: 'Voluntariado y Activismo',
    },
    de: {
      sportsFitness: 'Sport und Fitness',
      travel: 'Reisen',
      musicEntertainment: 'Musik und Unterhaltung',
      artsCreativity: 'Kunst und Kreativität',
      readingLearning: 'Lesen und Lernen',
      technologyGaming: 'Technologie und Spiele',
      foodCooking: 'Essen und Kochen',
      natureOutdoors: 'Natur und Draußen',
      socializingRelationships: 'Geselligkeit und Beziehungen',
      fashionStyle: 'Mode und Stil',
      healthWellness: 'Gesundheit und Wohlbefinden',
      diyCrafts: 'DIY und Handwerk',
      petsAnimalCare: 'Haustiere und Tierpflege',
      carsAutomobiles: 'Autos und Automobile',
      historyArchaeology: 'Geschichte und Archäologie',
      financeInvesting: 'Finanzen und Investieren',
      scienceDiscovery: 'Wissenschaft und Entdeckung',
      philosophySpirituality: 'Philosophie und Spiritualität',
      volunteeringActivism: 'Freiwilligenarbeit und Aktivismus',
    },
    fr: {
      sportsFitness: 'Sports et Fitness',
      travel: 'Voyages',
      musicEntertainment: 'Musique et Divertissement',
      artsCreativity: 'Arts et Créativité',
      readingLearning: 'Lecture et Apprentissage',
      technologyGaming: 'Technologie et Jeux',
      foodCooking: 'Nourriture et Cuisine',
      natureOutdoors: 'Nature et Plein Air',
      socializingRelationships: 'Sociabilité et Relations',
      fashionStyle: 'Mode et Style',
      healthWellness: 'Santé et Bien-être',
      diyCrafts: 'Bricolage et Artisanat',
      petsAnimalCare: 'Animaux de Compagnie et Soins des Animaux',
      carsAutomobiles: 'Voitures et Automobiles',
      historyArchaeology: 'Histoire et Archéologie',
      financeInvesting: 'Finance et Investissement',
      scienceDiscovery: 'Science et Découverte',
      philosophySpirituality: 'Philosophie et Spiritualité',
      volunteeringActivism: 'Bénévolat et Activisme',
    },
    it: {
      sportsFitness: 'Sport e Fitness',
      travel: 'Viaggi',
      musicEntertainment: 'Musica e Intrattenimento',
      artsCreativity: 'Arte e Creatività',
      readingLearning: 'Lettura e Apprendimento',
      technologyGaming: 'Tecnologia e Videogiochi',
      foodCooking: 'Cibo e Cucina',
      natureOutdoors: "Natura e Attività all'Aperto",
      socializingRelationships: 'Società e Relazioni',
      fashionStyle: 'Moda e Stile',
      healthWellness: 'Salute e Benessere',
      diyCrafts: 'Fai da Te e Artigianato',
      petsAnimalCare: 'Animali Domestici e Cura degli Animali',
      carsAutomobiles: 'Auto e Automobili',
      historyArchaeology: 'Storia e Archeologia',
      financeInvesting: 'Finanza e Investimenti',
      scienceDiscovery: 'Scienza e Scoperte',
      philosophySpirituality: 'Filosofia e Spiritualità',
      volunteeringActivism: 'Volontariato e Attivismo',
    },
    pt: {
      sportsFitness: 'Esportes e Fitness',
      travel: 'Viagem',
      musicEntertainment: 'Música e Entretenimento',
      artsCreativity: 'Artes e Criatividade',
      readingLearning: 'Leitura e Aprendizagem',
      technologyGaming: 'Tecnologia e Jogos',
      foodCooking: 'Comida e Culinária',
      natureOutdoors: 'Natureza e Ar Livre',
      socializingRelationships: 'Convívio e Relacionamentos',
      fashionStyle: 'Moda e Estilo',
      healthWellness: 'Saúde e Bem-estar',
      diyCrafts: 'Faça Você Mesmo e Artesanato',
      petsAnimalCare: 'Animais de Estimação e Cuidados com Animais',
      carsAutomobiles: 'Carros e Automóveis',
      historyArchaeology: 'História e Arqueologia',
      financeInvesting: 'Finanças e Investimentos',
      scienceDiscovery: 'Ciência e Descoberta',
      philosophySpirituality: 'Filosofia e Espiritualidade',
      volunteeringActivism: 'Voluntariado e Ativismo',
    },
  };

  const interests: HobbiesInfo[] = [];

  Object.keys(interestsNames.en).forEach((code) => {
    const name = interestsNames[language]?.[code] || 'Unknown';
    interests.push({ code, name });
  });

  return interests;
};
