import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './../globals.css';
import { QuestionnaireProvider } from '../context/QuestionnaireContext';
import FirebaseInit from './fireBaseInit';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string; };
}>) {
  return (
    <html lang={locale}>
      <FirebaseInit>
        <QuestionnaireProvider>
          <body className={inter.className}>{children}</body>
        </QuestionnaireProvider>
      </FirebaseInit>
    </html>
  );
}
